### ISSUE TITLE
track_running_stats参数设置的问题

### ISSUE THREAD

**Issue by cxmscb** [vignywang/CNDesc#2]
你好，感谢代码的开源，有两个问题请教一下。
1.cross norm中的track_running_stats是设置为False吗？
2.cross norm的输出是否还需要加L2 norm，因为用到了余弦距离。

**Comment by vignywang** [comment]
1.是的，不过我们没有探索过这个参数，不知道使用True会不会更好。
2.我们所有损失都是欧式距离（参见CNDesc/utils/utils.py），所以不需要再做L2 normalization。

**Comment by cxmscb** [comment]
> 1.是的，不过我们没有探索过这个参数，不知道使用True会不会更好。 2.我们所有损失都是欧式距离（参见CNDesc/utils/utils.py），所以不需要再做L2 normalization。

感谢很及时的回复。对于第二点，我发现训练时使用的是欧式距离，但HPatches测评时用的是余弦相似度，所以才会有这个疑问。

**Comment by vignywang** [comment]
感谢您的提醒。描述子匹配使用常见的互为最近邻匹配，测评代码中使用余弦相似度的方式来计算欧式距离，我们与之前方法一样，没有做任何修改。 从效果上来看，使用cross归一化的描述子使用默认代码匹配仍然可以正常工作。我们建议使用欧式距离匹配试一下，可能会有更好的匹配性能。感觉这个匹配度量并不是十分严格。类似地，r2d2从归一化的特征图上采样亚像素位置的描述子直接用于匹配，它的描述子在数值上也不是严格l2归一化的，理论上也不能使用余弦相似度计算欧式距离。

**Comment by cxmscb** [comment]
谢谢你的回复!!!有个问题请教一下，我发现CNDesc和MTLDesc在网络结构上都没有用到Batch Norm，请问这个有什么解释吗？

**Comment by vignywang** [comment]
我们追随SuperPoint的设定没有使用Batch Norm，不排除添加后会带来性能提升。当然其他可以应用到中间层的归一化方法也可以试一下，HyNet: Learning Local Descriptor with Hybrid Similarity Measure and Triplet Loss好像做过类似的改进。但我觉得中间层的Batch Norm还是为了让损失更好地优化，如果损失本身优化地很好，可以不去考虑这个。用不用BN可能取决于网络的深度，数据集样本间的差异性，batch size大小，学习率的选取，我觉得还是以实际训练效果为依据。并且还取决于特定任务或者架构，像Instance Normalization对图像风格迁移很重要，Layer Normalization对Transfomer很重要。
